title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 You can update description in update blog details page.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bpmottathai.github.io/testrr" # the base hostname & protocol for your site
twitter_username: jekyllrb

markdown: kramdown

name: Your awesome title

date: 2018-10-19 11:15:30 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: https://bpmottathai.github.io/testrr/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 
# Details for the RSS feed generator
author:        testrr
